# Generated by Django 4.2.11 on 2024-03-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_alter_comment_com_dislike_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='post',
        ),
    ]
